/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RSM1_H_RPCGEN
#define _RSM1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define TESTPROG1 1
#define VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define DATE 1
extern  char ** date_1(long *, CLIENT *);
extern  char ** date_1_svc(long *, struct svc_req *);
extern int testprog1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DATE 1
extern  char ** date_1();
extern  char ** date_1_svc();
extern int testprog1_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RSM1_H_RPCGEN */
